version: '3.1'

services:
  web:
    image: 'captacion-php'
    ports:
      - '8000:8000'
    volumes:
      - ./:/app
    command: php artisan serve --host=0.0.0.0
    links:
      - "mailtrap"
      - "mysql"

  mysql:
    image: 'mysql:8.0.19'
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
    ports:
      - '3306:3306'
    volumes:
      - 'mysql-data:/var/lib/mysql'

  mailtrap:
    image: 'eaudeweb/mailtrap'
    command: '-d'
    ports:
      - '8081:80'

volumes:
  mysql-data:
